In [1]:
import numpy as np

arr = [5,5,0,5
    ,5,0,3,4
    ,3,4,0,3
    ,0,0,5,3
    ,5,4,4,5
    ,5,4,5,5]
arr_6_4 = np.reshape(arr,newshape=[6,4])
print(arr_6_4,end='\n\n')

[[5 5 0 5]
 [5 0 3 4]
 [3 4 0 3]
 [0 0 5 3]
 [5 4 4 5]
 [5 4 5 5]]



In [2]:
# [U,singular,Vtranspose]=svd(A)
# 代码参考: https://blog.csdn.net/kbccs/article/details/82590032
U, singular, V_transpose = np.linalg.svd(arr_6_4) # SVD

decimal = 4
U , singular, V_transpose= np.round(U,decimal), np.round(singular,decimal), np.round(V_transpose,decimal) 
print('U Matrix: ',U ,end='\n\n')
# singular = np.linalg.multi_dot([np.eye(6, 4,k=0), singular])

print(singular)


U Matrix:  [[-0.4472 -0.5373 -0.0064 -0.5037 -0.3857 -0.3298]
 [-0.3586  0.2461  0.8622 -0.1458  0.078   0.2002]
 [-0.2925 -0.4033 -0.2275 -0.1038  0.436   0.7065]
 [-0.2078  0.67   -0.3951 -0.5888  0.026   0.0667]
 [-0.5099  0.0597 -0.1097  0.2869  0.5946 -0.5371]
 [-0.5316  0.1887 -0.1914  0.5341 -0.5485  0.2429]]

[17.7139  6.3917  3.098   1.329 ]


In [3]:
data = np.eye(6,4,k=0)
print(data,end='\n\n')

data = np.multiply(data, singular) # Vector 转换为 Matrix

singular_matrix = data
print('singular Matrix: \n',singular_matrix ,end='\n\n')
# 转置矩阵: https://zh.wikipedia.org/wiki/%E8%BD%AC%E7%BD%AE%E7%9F%A9%E9%98%B5
print('V_transpose Matrix: \n',V_transpose ,end='\n\n')

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

singular Matrix: 
 [[17.7139  0.      0.      0.    ]
 [ 0.      6.3917  0.      0.    ]
 [ 0.      0.      3.098   0.    ]
 [ 0.      0.      0.      1.329 ]
 [ 0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.    ]]

V_transpose Matrix: 
 [[-0.571  -0.4275 -0.3846 -0.5859]
 [-0.2228 -0.5172  0.8246  0.0532]
 [ 0.6749 -0.6929 -0.2532  0.014 ]
 [ 0.4109  0.2637  0.3286 -0.8085]]



In [4]:
k = 2 # Latent Factor
# 
svd_answer = np.linalg.multi_dot(arrays=[U[:,0:k],singular_matrix[:k,:k],V_transpose[0:k,:]])
print('svd_answer: \n',svd_answer.round(4))

svd_answer: 
 [[ 5.2884  5.1627  0.2148  4.4586]
 [ 3.2766  1.902   3.7402  3.8054]
 [ 3.5329  3.5482 -0.1329  2.8986]
 [ 1.1477 -0.6413  4.947   2.3845]
 [ 5.0724  3.664   3.7885  5.3123]
 [ 5.1082  3.4018  4.6162  5.5814]]
